version: '14.9'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Qwerty123!
            - POSTGRES_DB=ecommerce
        ports: 
            - 5430:5430
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=ipsitamohapatra93@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=Qwerty123!
        ports: 
            - "5050:80"